#!/bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions


# Adds alias to global zshrc
if [ -z /etc/zsh/zshrc ]; then
    log_daemon_msg "Creating zsh alias..."
    if echo "alias credit='/usr/local/share/cc/cc.py'" >> /etc/zsh/zshrc; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
fi

# Adds alias to global bash
if [ -z /etc/bash.bashrc ]; then
    log_daemon_msg "Creating bash alias..."
    if echo "alias credit='/usr/local/share/cc/cc.py'" >> /etc/bash.bashrc; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
fi
